[
  {
    "id": 1,
    "korean_name": "스투키",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "물 주기는 한 달에 한 번도 충분합니다. 과습 주의!",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 물렁해지며 검게 변색되면 과습입니다. 뿌리를 말려주세요."
  },
  {
    "id": 2,
    "korean_name": "산세베리아",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "공기정화 능력이 탁월하며, 건조한 환경을 선호합니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "느림",
    "discoloration_tip": "노랗게 변색되면 물을 너무 자주 준 것입니다. 완전히 마른 후 주세요."
  },
  {
    "id": 3,
    "korean_name": "금전수",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "중",
    "management_tip": "어두운 곳에서도 잘 자라며, 물을 자주 주면 안 됩니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 검은 반점으로 변하면 통풍 불량과 과습이 겹친 것입니다. 환기시키세요."
  },
  {
    "id": 4,
    "korean_name": "몬스테라",
    "difficulty": "중",
    "light_level": "중간",
    "size": "대",
    "management_tip": "잎이 크고 관리가 쉬우며, 잎에 분무를 해주면 좋습니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "잎 끝이 갈변하면 건조하거나 물 부족 신호입니다. 물을 흠뻑 주세요."
  },
  {
    "id": 5,
    "korean_name": "아레카 야자",
    "difficulty": "중",
    "light_level": "중간",
    "size": "대",
    "management_tip": "실내 습도 조절에 탁월하며, 통풍이 잘 되어야 합니다.",
    "air_purifying": "높음",
    "pet_safe": "안전",
    "growth_speed": "보통",
    "discoloration_tip": "잎 끝이 마르고 갈색으로 변하면 습도가 너무 낮은 것입니다. 분무를 자주 해주세요."
  },
  {
    "id": 6,
    "korean_name": "테이블 야자",
    "difficulty": "하",
    "light_level": "중간",
    "size": "중",
    "management_tip": "작고 튼튼하며, 밝은 간접광을 좋아합니다.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 얇고 연해지면 빛이 부족한 신호입니다. 조금 더 밝은 곳으로 옮기세요."
  },
  {
    "id": 7,
    "korean_name": "아이비",
    "difficulty": "하",
    "light_level": "중간",
    "size": "소",
    "management_tip": "덩굴성 식물로, 실내 어디든 잘 적응합니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 축 처지고 색이 바래면 물을 너무 오래 안 준 것입니다. 즉시 물을 주세요."
  },
  {
    "id": 8,
    "korean_name": "호야",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "성장이 느리지만 튼튼하며, 건조하게 관리합니다.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 쭈글쭈글해지면 물 부족입니다. 물을 줘도 회복이 안 되면 뿌리 상태를 확인하세요."
  },
  {
    "id": 9,
    "korean_name": "스킨답서스",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "공기정화 능력이 우수하고, 키우기 가장 쉽습니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 노랗게 변하면 과습 신호입니다. 흙이 완전히 마른 후 물을 주세요."
  },
  {
    "id": 10,
    "korean_name": "고무나무",
    "difficulty": "중",
    "light_level": "중간",
    "size": "대",
    "management_tip": "잎을 닦아주면 광택이 살아나고 병해충 예방에 좋습니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "새 잎이 작고 흐릿하면 빛이 부족하거나 영양 부족일 수 있습니다. 비료를 주거나 밝은 곳으로 옮기세요."
  },
  {
    "id": 11,
    "korean_name": "뱅갈고무나무",
    "difficulty": "중",
    "light_level": "밝음",
    "size": "대",
    "management_tip": "밝은 빛을 좋아하며, 잎이 아름다운 관상용 식물입니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "잎의 무늬가 사라지고 녹색만 남으면 빛이 너무 부족한 것입니다."
  },
  {
    "id": 12,
    "korean_name": "선인장",
    "difficulty": "하",
    "light_level": "밝음",
    "size": "소",
    "management_tip": "물은 매우 드물게 주고, 빛이 잘 드는 곳에 두세요. 과습이 치명적입니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "몸체가 물컹해지거나 갈색으로 변하면 썩는 중입니다. 환기를 시키고 물을 끊으세요."
  },
  {
    "id": 13,
    "korean_name": "다육식물",
    "difficulty": "하",
    "light_level": "밝음",
    "size": "소",
    "management_tip": "다양한 종류가 있으며, 햇빛이 부족하면 웃자랍니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 쭈글거리면 물 부족입니다. 만약 물을 줬는데도 물렁하면 과습일 수 있습니다."
  },
  {
    "id": 14,
    "korean_name": "군자란",
    "difficulty": "중",
    "light_level": "중간",
    "size": "소",
    "management_tip": "봄에 아름다운 꽃을 피우며, 직사광선은 피해야 합니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "느림",
    "discoloration_tip": "잎에 검은 점이 생기면 병해 신호일 수 있습니다. 소독제를 사용해 닦아주세요."
  },
  {
    "id": 15,
    "korean_name": "칼라데아",
    "difficulty": "상",
    "light_level": "낮음",
    "size": "중",
    "management_tip": "습도를 매우 좋아하며, 물 마르는 것에 민감합니다. 잎에 자주 분무해 주세요.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "보통",
    "discoloration_tip": "잎 끝이 타는 것처럼 마르면 습도가 너무 낮은 것입니다. 가습기를 틀어주세요."
  },
  {
    "id": 16,
    "korean_name": "마란타",
    "difficulty": "상",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "잎이 밤에 접히는 특징이 있으며, 건조하면 잎이 말립니다.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "보통",
    "discoloration_tip": "잎이 갑자기 노란색으로 변하면 물이 너무 많거나 너무 차가운 물을 사용한 것입니다."
  },
  {
    "id": 17,
    "korean_name": "율마",
    "difficulty": "상",
    "light_level": "밝음",
    "size": "대",
    "management_tip": "향이 좋지만, 물을 좋아하고 통풍이 필수입니다.",
    "air_purifying": "높음",
    "pet_safe": "안전",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 전체적으로 갈색으로 마르면 물 부족 혹은 심각한 통풍 불량입니다. 환기를 시키세요."
  },
  {
    "id": 18,
    "korean_name": "제라늄",
    "difficulty": "중",
    "light_level": "밝음",
    "size": "소",
    "management_tip": "꽃이 잘 피며, 겉흙이 마르면 물을 흠뻑 주세요.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "빠름",
    "discoloration_tip": "잎 가장자리가 노랗게 변하면 과습일 수 있으니, 다음 물주기를 늦추세요."
  },
  {
    "id": 19,
    "korean_name": "백합",
    "difficulty": "상",
    "light_level": "중간",
    "size": "중",
    "management_tip": "화려한 꽃이 특징이며, 물과 영양 관리가 필요합니다.",
    "air_purifying": "낮음",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "줄기가 약해지고 잎이 처지면 병해 가능성이 있습니다. 영양제를 줍니다."
  },
  {
    "id": 20,
    "korean_name": "호접란",
    "difficulty": "상",
    "light_level": "중간",
    "size": "소",
    "management_tip": "고급 난 종류로, 온도와 습도 관리에 신경 써야 합니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "뿌리가 검게 변하면 썩은 것입니다. 썩은 뿌리를 제거하고 물을 조절합니다."
  },
  {
    "id": 21,
    "korean_name": "행운목",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "중",
    "management_tip": "물에 담가 키울 수도 있으며, 매우 기르기 쉽습니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "느림",
    "discoloration_tip": "줄기가 물컹해지면 썩는 중입니다. 윗부분을 잘라내고 물을 갈아주세요."
  },
  {
    "id": 22,
    "korean_name": "틸란드시아",
    "difficulty": "하",
    "light_level": "중간",
    "size": "소",
    "management_tip": "흙 없이 공중에서 기릅니다. 일주일에 1~2회 물에 담가 관리합니다.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 검게 변하면 썩은 것입니다. 물에 담근 후 통풍을 잘 시키세요."
  },
  {
    "id": 23,
    "korean_name": "로즈마리",
    "difficulty": "중",
    "light_level": "밝음",
    "size": "중",
    "management_tip": "허브류로 향이 좋고, 햇빛과 통풍이 필수입니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "보통",
    "discoloration_tip": "잎이 노랗게 변하고 떨어지면 물이 부족하거나 통풍이 불량합니다. 햇빛과 환기를 늘려주세요."
  },
  {
    "id": 24,
    "korean_name": "레몬밤",
    "difficulty": "중",
    "light_level": "밝음",
    "size": "소",
    "management_tip": "차로도 이용하며, 물을 좋아하지만 배수가 잘 되어야 합니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 갈변하면 건조하거나 햇빛이 너무 강한 것입니다. 반그늘로 옮겨주세요."
  },
  {
    "id": 25,
    "korean_name": "알로카시아",
    "difficulty": "중",
    "light_level": "중간",
    "size": "대",
    "management_tip": "잎이 커서 관상 가치가 높고, 습도 관리에 유의해야 합니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "빠름",
    "discoloration_tip": "잎에 물방울이 맺히면 물을 너무 많이 준 것입니다. 물 주기를 조절하세요."
  },
  {
    "id": 26,
    "korean_name": "크로톤",
    "difficulty": "중",
    "light_level": "밝음",
    "size": "중",
    "management_tip": "잎의 색이 화려하며, 색을 유지하려면 많은 빛이 필요합니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "색이 바래면 빛 부족입니다. 직사광선을 피한 밝은 창가로 옮기세요."
  },
  {
    "id": 27,
    "korean_name": "싱고니움",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "습도가 낮아도 잘 자라며, 초보자에게 적합합니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "잎이 작고 연해지면 빛이 부족하다는 뜻입니다. 밝은 간접광을 주세요."
  },
  {
    "id": 28,
    "korean_name": "아라우카리아",
    "difficulty": "중",
    "light_level": "중간",
    "size": "대",
    "management_tip": "작은 트리 모양이며, 겨울에도 잘 견디는 편입니다.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "가지가 아래로 처지면 물이 부족한 것입니다. 물을 충분히 주세요."
  },
  {
    "id": 29,
    "korean_name": "만데빌라",
    "difficulty": "상",
    "light_level": "밝음",
    "size": "중",
    "management_tip": "화려한 꽃이 피며, 햇빛과 따뜻한 환경을 좋아합니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 노랗게 변하면서 떨어지면 통풍이 불량하거나 빛이 부족한 것입니다."
  },
  {
    "id": 30,
    "korean_name": "스파티필름",
    "difficulty": "중",
    "light_level": "낮음",
    "size": "중",
    "management_tip": "물 부족 시 잎이 처지는 것으로 알 수 있어 관리하기 쉽습니다. 흰 꽃이 핍니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "잎 끝이 갈색으로 변하면 물에 염소 성분이 많거나 습도가 낮은 것입니다. 정수된 물을 사용하세요."
  },
  {
    "id": 31,
    "korean_name": "호접란",
    "difficulty": "상",
    "light_level": "중간",
    "size": "소",
    "management_tip": "고급 난 종류로, 온도와 습도 관리에 신경 써야 합니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 흐물흐물해지면 과습으로 뿌리가 썩은 것입니다. 즉시 분갈이하세요."
  },
  {
    "id": 32,
    "korean_name": "안스리움",
    "difficulty": "중",
    "light_level": "중간",
    "size": "중",
    "management_tip": "독특한 꽃이 오래 피며, 흙이 마르기 전에 물을 주는 것이 좋습니다.",
    "air_purifying": "높음",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "잎이 쭈글거리고 꽃이 시들면 물 부족이나 영양 부족입니다. 물과 영양제를 함께 주세요."
  },
  {
    "id": 33,
    "korean_name": "아이콘사발야자",
    "difficulty": "중",
    "light_level": "중간",
    "size": "중",
    "management_tip": "밝은 간접광에서 잘 자라며, 흙이 마르면 물을 줍니다.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "보통",
    "discoloration_tip": "잎 끝이 갈색으로 타면 물 부족 또는 습도 부족입니다. 물을 보충하세요."
  },
  {
    "id": 34,
    "korean_name": "립살리스",
    "difficulty": "하",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "건조에 강한 선인장 종류로, 밝은 직사광선을 피합니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "줄기가 쪼글거리면 물 부족입니다. 너무 딱딱하고 색이 변하면 과습일 수 있습니다."
  },
  {
    "id": 35,
    "korean_name": "필레아 페페로미오이데스",
    "difficulty": "중",
    "light_level": "밝음",
    "size": "소",
    "management_tip": "빛을 따라 잎이 휘므로, 주기적으로 화분을 돌려주세요.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 안쪽으로 말리면 물 부족, 검은 반점은 과습 신호입니다."
  },
  {
    "id": 36,
    "korean_name": "피토니아",
    "difficulty": "상",
    "light_level": "낮음",
    "size": "소",
    "management_tip": "물을 매우 좋아하며, 흙이 마르면 극적으로 시듭니다. 즉시 물을 주세요.",
    "air_purifying": "보통",
    "pet_safe": "안전",
    "growth_speed": "보통",
    "discoloration_tip": "잎이 창백해지면 빛이 너무 강한 것입니다. 반그늘로 옮겨주세요."
  },
  {
    "id": 37,
    "korean_name": "보스턴 고사리",
    "difficulty": "중",
    "light_level": "중간",
    "size": "중",
    "management_tip": "습도를 매우 좋아하므로, 욕실 등 습한 곳에 두는 것이 좋습니다.",
    "air_purifying": "높음",
    "pet_safe": "안전",
    "growth_speed": "빠름",
    "discoloration_tip": "잎이 전체적으로 건조해지면 습도 부족과 물 부족입니다. 분무와 물주기를 늘리세요."
  },
  {
    "id": 38,
    "korean_name": "마지나타 (드라세나)",
    "difficulty": "하",
    "light_level": "중간",
    "size": "대",
    "management_tip": "줄기가 가늘고 길게 자라며, 실내에서 키우기 쉽습니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "느림",
    "discoloration_tip": "잎이 갑자기 떨어지면 급격한 온도 변화가 원인일 수 있습니다. 따뜻한 곳으로 옮기세요."
  },
  {
    "id": 39,
    "korean_name": "수염틸란드시아",
    "difficulty": "하",
    "light_level": "중간",
    "size": "소",
    "management_tip": "매일 분무해주거나 일주일에 1회 물에 담가 관리합니다.",
    "air_purifying": "낮음",
    "pet_safe": "안전",
    "growth_speed": "느림",
    "discoloration_tip": "줄기가 검게 변하면 통풍이 잘 안 되어 썩는 것입니다. 환기 공간에 걸어두세요."
  },
  {
    "id": 40,
    "korean_name": "크루시아",
    "difficulty": "중",
    "light_level": "중간",
    "size": "대",
    "management_tip": "잎이 두껍고 광택이 나며, 공기가 잘 통하는 곳을 좋아합니다.",
    "air_purifying": "보통",
    "pet_safe": "주의",
    "growth_speed": "보통",
    "discoloration_tip": "잎이 끈적해지면 진딧물 등 해충의 공격일 수 있습니다. 살충제로 닦아주세요."
  }
]
